title: 'Auto Clicker - AutoFill'
baseURL: 'https://docs.getbootstrap.com'

docsDir: 'site'

subtitle: 'Extension to automate click / fill.'

description: 'Extension to automate click / fill.'
authors: 'Dhruv Patel, Dharmesh Patel, and AutoClicker contributors'
author: 'Dhruv Techapps'
logo: '/docs/3.x/assets/brand/bootstrap-social-logo.png'
header: 'Auto Clicker - AutoFill'
facebook: 'dhruv.techapps'
instagram: 'dharmeshhemaram'
github: 'Dhruv-Techapps'
current_version: '4.0.47'
docs_version: '4.x'
github_org: 'https://github.com/Dhruv-Techapps'
discussion: 'https://github.com/Dhruv-Techapps/auto-clicker-auto-fill/discussions'
issues: 'https://github.com/Dhruv-Techapps/auto-clicker-auto-fill/issues'
repo: 'https://github.com/Dhruv-Techapps/auto-clicker-auto-fill'
x: 'dharmeshhemaram'
discord: 'https://discord.gg/ubMBeX3'
google_group: 'https://groups.google.com/g/auto-clicker-autofill'
opencollective: 'https://opencollective.com/auto-clicker-autofill'
youtube: 'https://www.youtube.com/@autoclickerautofill'
blog: 'https://blog.getautoclicker.com/'
configs: 'https://configs.getautoclicker.com'
data_entry: 'https://getdataentry.com/docs/3.x/getting-started/introduction/'
schedule_url: 'https://scheduleurl.com/docs/1.x/getting-started/introduction/'
stable: 'https://stable.getautoclicker.com'
beta: 'https://beta.getautoclicker.com'
dev: 'https://dev.getautoclicker.com'
test: 'https://test.getautoclicker.com'

analytics:
  container_id: 'GTM-K48RLHS'

algolia:
  app_id: 'S4D9IW396R'
  api_key: 'fe1f65f50add035126bcff7d278820d1'
  index_name: 'test-getautoclicker'

download:
  source: 'https://github.com/twbs/bootstrap/archive/v5.3.7.zip'
  dist: 'https://github.com/twbs/bootstrap/releases/download/v5.3.7/bootstrap-5.3.7-dist.zip'
  dist_examples: 'https://github.com/twbs/bootstrap/releases/download/v5.3.7/bootstrap-5.3.7-examples.zip'
  stable: 'https://chrome.google.com/webstore/detail/iapifmceeokikomajpccajhjpacjmibe'
  beta: 'https://chrome.google.com/webstore/detail/nmcpliniiebkbdehpgicgfcidgkpepep'
  dev: 'https://chrome.google.com/webstore/detail/cpjikgcdmhfnmaiibplplldlchbjejel'

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css'
  css_hash: 'sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr'
  css_rtl: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.rtl.min.css'
  css_rtl_hash: 'sha384-Xbg45MqvDIk1e563NLpGEulpX6AvL404DP+/iCgW9eFa2BqztiwTexswJo2jLMue'
  js: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js'
  js_hash: 'sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK'
  js_bundle: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js'
  js_bundle_hash: 'sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q'
  popper: 'https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js'
  popper_hash: 'sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r'
  popper_esm: 'https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js'

anchors:
  min: 2
  max: 5

toc:
  min: 2
  max: 3
