name: Deploy [CDN]
run-name: Deploy to CDN by @${{ github.actor }} on ${{ inputs.version || github.ref_name }}

on:
  workflow_dispatch:

jobs:
  main:
    name: Build & Bundle & Publish
    environment:
      name: ${{inputs.environment}}
      url: ${{ steps.release.outputs.url}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      discussions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: I18n deploy to firebase hosting
        if: ${{ inputs.upload_i18n }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: auto-clicker-autofill
          target: auto-clicker-auto-fill-static
          channelId: live
